src/edu/umsl/keyword/beans/KeywordBean.java
package edu.umsl.keyword.beans;

public class KeywordBean
{
	private String keyword, content, bookTitle, authors;
	private int count, edition, year, kid, itemid, sourceid;

	public void setKeyword(String name )
	{
		keyword = name;  
	}
	   
	public String getKeyword()
	{
		return keyword;  
	}
	   
	public void setContent(String name)
	{
		content = name;
	}
	   
	public String getContent()
	{
		return content;
	}
	   
	public void setCount(int num)
	{
		count = num;
	}
	
	public int getCount()
	{
		return count;
	}
	
	public void setKid(int num)
	{
		kid = num;
	}
	
	public int getKid()
	{
		return kid;
	}
	
	public void setItemId(int num)
	{
		itemid = num;
	}
	
	public int getItemId()
	{
		return itemid;
	}
	
	public void setSourceId(int num)
	{
		sourceid = num;
	}
	
	public int getSourceId()
	{
		return sourceid;
	}
	
	public void setBookTitle(String title)
	{
		bookTitle = title;
	}
	
	public String getBookTitle()
	{
		return bookTitle;
	}
	
	public void setAuthor(String author)
	{
		authors = author;
	}
	
	public String getAuthors()
	{
		return authors;
	}
	
	public void setYear(int year)
	{
		this.year = year;
	}
	
	public int getYear()
	{
		return year;
	}
	
	public void setEdition (int num)
	{
		edition = num;
	}
	
	public int getEdition()
	{
		return edition;
	}
}

src/edu/umsl/keyword/beans/KeywordDataBean.java
package edu.umsl.keyword.beans;

import java.sql.*;
import java.util.*;

public class KeywordDataBean
{
	private Connection connection;
	private PreparedStatement getTheories;
	
	public KeywordDataBean(String keyword) throws Exception
	{
		try
		{
			Class.forName("com.mysql.jdbc.Driver");
			connection = DriverManager.getConnection(
					"jdbc:mysql://localhost:3306/keyworddb", "root", "");
			
			
			getTheories = connection.prepareStatement("SELECT kid FROM keyword WHERE keyword_name = ?");
			getTheories.setString(1, keyword);
		}
		catch (SQLException sqle)
		{
			sqle.printStackTrace();
		}
	}
	
	public List<KeywordBean> getKeywords() throws SQLException
	{
		int i = 0, count = 0;
		List<KeywordBean> list = new LinkedList<KeywordBean>();
		List<Integer> idList = new ArrayList<Integer>();
		KeywordBean bean = new KeywordBean();
		ResultSet results = getTheories.executeQuery();

		while(results.next())
		{
			bean.setKid(results.getInt(1));
		}
		
		getTheories = connection.prepareStatement("SELECT item_id FROM single_keyword_mapping WHERE keyword_id = ?");
		getTheories.setInt(1,  bean.getKid());
		
		results = getTheories.executeQuery();

		while(results.next())
		{
			KeywordBean bean2 = new KeywordBean();
			bean2.setKid(bean.getKid());
			bean2.setItemId(results.getInt(1));
			list.add(bean2);
		}
		
		getTheories = connection.prepareStatement("SELECT source_id, content FROM my_theory WHERE mtid = ?");
		
		while (i < list.size())
		{
			getTheories.setInt(1, list.get(i).getItemId());
			results = getTheories.executeQuery();
			
			while(results.next())
			{
				if (idList.contains(results.getInt(1)))
				{
					list.remove(i);
					i--;
					count++;
				}
				else
				{
					
					idList.add(results.getInt(1));
					list.get(i).setSourceId(results.getInt(1));
					list.get(i).setContent(results.getString(1));
					count = 0;
				}
				list.get(i).setCount(count + 1);
			}
			i++;
		}

		getTheories = connection.prepareStatement("SELECT book_title, authors, edition_number, year_number FROM book WHERE bid = ?");
		
		i = 0;
		while (i < list.size())
		{	
			getTheories.setInt(1,  list.get(i).getSourceId());
			results = getTheories.executeQuery();
			
			while(results.next())
			{
				list.get(i).setBookTitle(results.getString(1));
				list.get(i).setAuthor(results.getString(2));
				list.get(i).setEdition(results.getInt(3));
				list.get(i).setYear(results.getInt(4));
			}
			i++;
		}
		
		return list;
	}
	
	protected void finalize()
	{
		try
		{
			getTheories.close();
		}
		catch (SQLException sqle)
		{
			sqle.printStackTrace();
		}
	}
}

src/edu/umsl/keyword/servlet/ContentServlet.java
package edu.umsl.keyword.servlet;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import edu.umsl.keyword.beans.*;

@WebServlet("/ContentServlet")
public class ContentServlet extends HttpServlet
{
	private static final long serialVersionUID = 1L;
       
    public ContentServlet()
    {
        super();
    }

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
	{
		String keyword = request.getParameter("bar");
		if (keyword.contains(","))
			keyword = keyword.substring(0, keyword.indexOf(","));
			
		RequestDispatcher dispatcher = 
                request.getRequestDispatcher("index.jsp");
		
		try
		{
			KeywordDataBean bean = new KeywordDataBean(keyword);
			List<KeywordBean> list = new ArrayList<KeywordBean>();
			list = bean.getKeywords();
			request.setAttribute("list", list);
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		
		dispatcher.forward(request, response);
	}
}

WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
		<title>Keyword Based Search</title>
		<style>
			body {
				color: #333333;
				margin: 0 auto;
				font-size: 1em;
				font-family: Verdana, "Verdana CE", Arial, "Arial CE",
					"Lucida Grande CE", lucida, "Helvetica CE", sans-serif;
				text-align: center;
			}
			
			table {
				width: 75%;
				align: center;
			}

			td, tr {
				border: 1px solid lightblue;
			}
			
			.indiv {
				position: relative;
				width: 27em;
				height: 10em;
				padding: 1em;
				overflow: auto;
			}
			
			.toprow {
				bgcolor: #ca502f;
				text-align: center;
				colspan: 4;
			}
		</style>
	</head>
	<body>
		<form id="keywordsearch" method="get" action="ContentServlet">
			<input type="text" name="bar" id="bar" size="21" maxlength="120" placeholder="Keywords for theory">
			<input type="submit" value="Search">
		</form>
		<table>
			<tr>
				<td align="center" colspan="4" bgcolor="#CA502F">Search Results</td>
			</tr>
			<c:forEach items="${list}" var="list">
				<tr>
					<td width="10%"><img src="img/plus.png"></td>
					<td width="10%">${list.count}</td>
					<td width="50%">${list.sourceId} ${list.bookTitle} (${list.authors})</td>
					<td width="30%">${list.edition}/${list.year}</td>
				</tr>
			</c:forEach>
			<tr>
				<td align="center" colspan="4" bgcolor="#CA502F">The End</td>
			</tr>
		</table>
	</body>
</html>